########################################################################
# cargo-deny configuration
# Goal: keep CI green while surfacing meaningful issues gradually.
# Generated: 2025-09-09
########################################################################

[graph]
all-features = true
features = []
no-default-features = false

[advisories]
version = 2
ignore = []            # RUSTSEC-XXXX-XXXX entries here
unmaintained = "workspace"   # fail only if direct dep
yanked = "warn"               # explicit (default warn)

[licenses]
version = 2
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "Unicode-DFS-2016",
  "Unicode-3.0",   # required by unicode-ident via chumsky
  "ISC",
  "Zlib",
]
confidence-threshold = 0.8   # still supported

[licenses.private]
ignore = true  # no license scan for path = { workspace = true }

[bans]
multiple-versions = "allow"   # relax initially; tighten later
wildcards = "deny"
highlight = "all"
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

# Per-crate overrides examples (uncomment + adjust):
#[[licenses.clarify]]
#name = "some-crate"
#version = "=1.2.3"
#expression = "MIT"
#license-files = ["LICENSE"]
