[package]
name = "lzscr-preast"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1", features = ["derive"] }
lzscr-lexer = { path = "../lzscr-lexer", version = "0.1.0" }
lzscr-ast = { path = "../lzscr-ast", version = "0.1.0" }
thiserror = "2"
