[package]
name = "lzscr-analyzer"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
lzscr-ast = { path = "../lzscr-ast", version = "0.1.0" }
lzscr-parser = { path = "../lzscr-parser", version = "0.1.0" }
ahash = "0.8"
serde = { version = "1", features = ["derive"] }
