# cargo-audit configuration (optional overrides)
[advisories]
ignore = []
# Optional examples:
# informational_warnings = ["unmaintained", "yanked"]
# severity_threshold = "medium"  # low|medium|high|critical
