[package]
name = "lzscr-runtime"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
lzscr-ast = { path = "../lzscr-ast", version = "0.1.0" }
thiserror = "2"

[dev-dependencies]
lzscr-parser = { path = "../lzscr-parser", version = "0.1.0" }
