[package]
name = "lzscr-coreir"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1", features = ["derive"] }
lzscr-ast = { path = "../lzscr-ast", version = "0.1.0" }
thiserror = "1"
